source("batch.R")
source("epochs.R")
source("generate_data.R")
source("LDR.R")
source("decay.R")
source("RCPP_gradient.R")
source("SGD.R")
library(CSwR)
X <- generate_x(1000, 2)
Y <- generate_y(X, 0.5, alpha = 1, beta = 3, gamma = 5, rho = 1)

SGD(par0 = c(3, 6, 3, 3),
    loss_gr = log_gradient(X, Y),
    N = length(X),
    batch = batch_random(replace = FALSE),
    epoch = epoch_batch_rcpp_partial(100, X, Y),
    gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
    loss = log_loss(X, Y),
    maxit = 300)


SGD2_tracer <- tracer("par")
SGD2(par0 = c(3, 6, 3, 3),
    loss_gr = log_gradient(X, Y),
    N = length(X),
    batch = batch_random(replace = FALSE),
    epoch = epoch_test(100),
    gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
    loss = log_loss(X, Y),
    maxit = 300)

SGD(par0 = c(3, 6, 3, 3),
    loss_gr = log_gradient(X, Y),
    N = length(X),
    batch = batch_random(replace = FALSE),
    epoch = epoch_batch(100),
    gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
    loss = log_loss(X, Y),
    maxit = 300)

library(bench)
bm <- mark(CR_FULL = SGD2(par0 = c(3, 6, 3, 3),
                          loss_gr = log_gradient(X, Y),
                          N = length(X),
                          batch = batch_random(replace = FALSE),
                          epoch = epoch_test(100),
                          gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                          loss = log_loss(X, Y),
                          maxit = 300),
           R_FULL = SGD(par0 = c(3, 6, 3, 3),
                        loss_gr = log_gradient(X, Y),
                        N = length(X),
                        batch = batch_random(replace = FALSE),
                        epoch = epoch_batch(100),
                        gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                        loss = log_loss(X, Y),
                        maxit = 300),
           R_RCPP_EGR = SGD(par0 = c(3, 6, 3, 3),
                            loss_gr = log_gradient(X, Y),
                            N = length(X),
                            batch = batch_random(replace = FALSE),
                            epoch = epoch_batch_rcpp_partial(100),
                            gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                            loss = log_loss(X, Y),
                            maxit = 300),
           R_RCPP_ERGR = SGD(par0 = c(3, 6, 3, 3),
                             loss_gr = log_gradient_rcpp(X, Y),
                             N = length(X),
                             batch = batch_random(replace = FALSE),
                             epoch = epoch_batch_rcpp_partial(100),
                             gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                             loss = log_loss(X, Y),
                             maxit = 300),
           RC_EPOCH = SGD(par0 = c(3, 6, 3, 3),
                          loss_gr = log_gradient(X, Y),
                          N = length(X),
                          batch = batch_random(replace = FALSE),
                          epoch = epoch_test(100),
                          gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                          loss = log_loss(X, Y),
                          maxit = 300),
           R_FULL_CGR = SGD(par0 = c(3, 6, 3, 3),
                            loss_gr = log_gradient_rcpp(X, Y),
                            N = length(X),
                            batch = batch_random(replace = FALSE),
                            epoch = epoch_batch(100),
                            gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                            loss = log_loss(X, Y),
                            maxit = 300),
           RC_E_CGR = SGD(par0 = c(3, 6, 3, 3),
                          loss_gr = log_gradient_rcpp(X, Y),
                          N = length(X),
                          batch = batch_random(replace = FALSE),
                          epoch = epoch_test(100),
                          gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                          loss = log_loss(X, Y),
                          maxit = 300),
           CR_FULL_GR = SGD2(par0 = c(3, 6, 3, 3),
                             loss_gr = log_gradient_rcpp(X, Y),
                             N = length(X),
                             batch = batch_random(replace = FALSE),
                             epoch = epoch_test(100),
                             gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                             loss = log_loss(X, Y),
                             maxit = 300),
           CPP_FULL = SGD(par0 = c(3, 6, 3, 3),
                          loss_gr = log_gradient_rcpp(X, Y),
                          N = length(X),
                          batch = batch_random(replace = FALSE),
                          epoch = epoch_batch_rcpp(100, X, Y),
                          gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                          loss = log_loss(X, Y),
                          maxit = 300),
            min_time = 20,
            check = FALSE)
library(ggplot2)
autoplot(bm)

microbenchmark::microbenchmark(CR_FULL = SGD2(par0 = c(3, 6, 3, 3),
                                              loss_gr = log_gradient(X, Y),
                                              N = length(X),
                                              batch = batch_random(replace = FALSE),
                                              epoch = epoch_test(100),
                                              gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                                              loss = log_loss(X, Y),
                                              maxit = 300),
                               R_FULL = SGD(par0 = c(3, 6, 3, 3),
                                            loss_gr = log_gradient(X, Y),
                                            N = length(X),
                                            batch = batch_random(replace = FALSE),
                                            epoch = epoch_batch(100),
                                            gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                                            loss = log_loss(X, Y),
                                            maxit = 300),
                               R_RCPP_EGR = SGD(par0 = c(3, 6, 3, 3),
                                            loss_gr = log_gradient(X, Y),
                                            N = length(X),
                                            batch = batch_random(replace = FALSE),
                                            epoch = epoch_batch_rcpp_partial(100),
                                            gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                                            loss = log_loss(X, Y),
                                            maxit = 300),
                               R_RCPP_ERGR = SGD(par0 = c(3, 6, 3, 3),
                                                loss_gr = log_gradient_rcpp(X, Y),
                                                N = length(X),
                                                batch = batch_random(replace = FALSE),
                                                epoch = epoch_batch_rcpp_partial(100),
                                                gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                                                loss = log_loss(X, Y),
                                                maxit = 300),
                               RC_EPOCH = SGD(par0 = c(3, 6, 3, 3),
                                              loss_gr = log_gradient(X, Y),
                                              N = length(X),
                                              batch = batch_random(replace = FALSE),
                                              epoch = epoch_test(100),
                                              gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                                              loss = log_loss(X, Y),
                                              maxit = 300),
                               R_FULL_CGR = SGD(par0 = c(3, 6, 3, 3),
                                                loss_gr = log_gradient_rcpp(X, Y),
                                                N = length(X),
                                                batch = batch_random(replace = FALSE),
                                                epoch = epoch_batch(100),
                                                gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                                                loss = log_loss(X, Y),
                                                maxit = 300),
                               RC_E_CGR = SGD(par0 = c(3, 6, 3, 3),
                                              loss_gr = log_gradient_rcpp(X, Y),
                                              N = length(X),
                                              batch = batch_random(replace = FALSE),
                                              epoch = epoch_test(100),
                                              gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                                              loss = log_loss(X, Y),
                                              maxit = 300),
                               CR_FULL_GR = SGD2(par0 = c(3, 6, 3, 3),
                                                 loss_gr = log_gradient_rcpp(X, Y),
                                                 N = length(X),
                                                 batch = batch_random(replace = FALSE),
                                                 epoch = epoch_test(100),
                                                 gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                                                 loss = log_loss(X, Y),
                                                 maxit = 300),
                               CPP_FULL = SGD(par0 = c(3, 6, 3, 3),
                                              loss_gr = log_gradient_rcpp(X, Y),
                                              N = length(X),
                                              batch = batch_random(replace = FALSE),
                                              epoch = epoch_batch_rcpp(100, X, Y),
                                              gamma0 = decay_scheduler(gamma0 = 1, gamma1 = 0.2, n1 = 300),
                                              loss = log_loss(X, Y),
                                              maxit = 300))
